# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Please write our copyright if you use this file.
# © 2023 Floorp Projects & Contributors

#! SELF HOST DOES NOT SUPPORTED
#TODO: separate Publish to other workflow

on:
  workflow_call:
    inputs:
      x86_64_artifact_name:
        type: string
        default: ""
      aarch64_artifact_name:
        type: string
        default: ""
      beta:
        type: boolean
        default: false
      MOZ_BUILD_DATE:
        type: string
        default: ""
    secrets:
        APPLE_DEVELOPER_P12_BASE64:
            description: "macOS CERTIFICATES P12 For App BASE64"
            required: true
        APPLE_DEVELOPER_P12_PASSWORD:
            description: "macOS CERTIFICATES P12 PASSWORD"
            required: true
        APPLE_DEVELOPER_ID:
            description: "macOS AppleDeveloperId"
            required: true
        APPLE_DEVELOPER_ACCOUNT_EMAIL:
            description: "macOS AppleAccountId"
            required: true
        APPLE_DEVELOPER_TEAM_ID:
            description: "macOS AppleTeamId"
            required: true
        APPLE_DEVELOPER_ACCOUNT_APP_SPESIFIC_PASSWORD:
            description: "macOS AppleAccountAppSpecificPassword"
            required: true

jobs:
  Integration:
    runs-on: macos-latest
    steps:
        - name: Delete SDK artifact
          uses: geekyeggo/delete-artifact@v5
          with:
            name: macos-sdk-package

        - name: Clone 📥
          uses: actions/checkout@v4
          with:
            submodules: 'recursive'

        - name: download AArch64 build artifact 📥
          uses: actions/download-artifact@v4
          with:
            name: ${{ inputs.aarch64_artifact_name }}
            path: ./

        - name: download x86_64 build artifact 📥
          uses: actions/download-artifact@v4
          with:
            name: ${{ inputs.x86_64_artifact_name }}
            path: ./

        - name: Extract 📦
          run: |
            brew install gnu-tar
            export PATH=/usr/local/opt/gnu-tar/libexec/gnubin:$PATH
            tar -xf ./floorp-x86_64-apple-darwin-with-pgo.tar.gz
            tar -xf ./floorp-aarch64-apple-darwin-with-pgo.tar.gz

        - uses: actions/setup-python@v5
          with:
            python-version: '3.11'

        - name: Check Branding Type
          shell: bash
          run: |
            if [[ $GHA_BETA == 'true' ]]; then
              export APP_NAME=`echo "Floorp Daylight"`
              echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
            else
              export APP_NAME=`echo "Floorp"`
              echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
            fi
          env:
            GHA_BETA: ${{ inputs.beta }}

        - name: Create environment 🌲
          shell: bash
          run: |
            ./mach --no-interactive bootstrap --application-choice browser
            echo -e "ac_add_options --enable-bootstrap" >> mozconfig
            ./mach configure

        - name: Install apple-codesign 🍎
          run: |
            cargo install apple-codesign

        - name: Extract .app from dmg 📦
          run: |
            rm -rf "./obj-x86_64-apple-darwin/dist/floorp/*.app"
            rm -rf "./obj-aarch64-apple-darwin/dist/floorp/*.app"

            hdiutil attach ./obj-x86_64-apple-darwin/dist/floorp*.mac.dmg
            cp -r "/Volumes/Floorp/${{ env.APP_NAME }}.app" ./obj-x86_64-apple-darwin/dist/floorp/

            hdiutil detach /Volumes/Floorp/

            hdiutil attach ./obj-aarch64-apple-darwin/dist/floorp*.mac.dmg
            cp -r "/Volumes/Floorp/${{ env.APP_NAME }}.app" ./obj-aarch64-apple-darwin/dist/floorp/

            hdiutil detach /Volumes/Floorp/

        - name: Integration 🗃
          run: |
            ./mach python "./toolkit/mozapps/installer/unify.py" "./obj-x86_64-apple-darwin/dist/floorp/${{ env.APP_NAME }}.app" "./obj-aarch64-apple-darwin/dist/floorp/${{ env.APP_NAME }}.app"

        - name: create .p12 for codesign 🖊️
          run: |
           echo ${{ secrets.APPLE_DEVELOPER_P12_BASE64 }} > floorp-cert.txt
           base64 --decode -i floorp-cert.txt -o floorpCert.p12
           echo ${{ secrets.APPLE_DEVELOPER_P12_PASSWORD }} > floorpCertPassword.passwd

        - name: Sign to .app 🖋️
          run: |
            ./mach macos-sign -v -r -c "release" -a "./obj-x86_64-apple-darwin/dist/floorp/${{ env.APP_NAME }}.app" --rcodesign-p12-file floorpCert.p12 --rcodesign-p12-password-file floorpCertPassword.passwd

        - name: Create DMG 📦
          run: |
            ./mach python -m mozbuild.action.make_dmg ./obj-x86_64-apple-darwin/dist/floorp floorp-macOS-universal-moz-artifact-release.dmg
            unzip "./.github/workflows/build/dmg-floorp-base.zip"
            hdiutil attach ./floorp-macOS-universal-moz-artifact-release.dmg
            hdiutil attach ./base.dmg

            cp -r "/Volumes/Floorp/${{ env.APP_NAME }}.app" /Volumes/Floorp\ Installer/
            hdiutil detach /Volumes/Floorp\ Installer/
            hdiutil convert ./base.dmg -format UDZO -imagekey zlib-level=9 -o floorp-macOS-universal-moz-artifact-dev.dmg

        - name: import APPLE DEVELOPER ID CERTIFICATE for .dmg 🔑
          uses: apple-actions/import-codesign-certs@v3
          with:
            p12-file-base64: ${{ secrets.APPLE_DEVELOPER_P12_BASE64 }}
            p12-password: ${{ secrets.APPLE_DEVELOPER_P12_PASSWORD }}

        - name: Sign to .dmg 🖋️
          run: |
            codesign -s "${{ secrets.APPLE_DEVELOPER_ID }}" floorp-macOS-universal-moz-artifact-dev.dmg

            xcrun notarytool submit "floorp-macOS-universal-moz-artifact.dmg" \
                --apple-id "${{ secrets.APPLE_DEVELOPER_ACCOUNT_EMAIL }}" \
                --team-id "${{ secrets.APPLE_DEVELOPER_TEAM_ID }}" \
                --password "${{ secrets.APPLE_DEVELOPER_ACCOUNT_APP_SPESIFIC_PASSWORD }}" \
                --wait

            mkdir -p ./output
            mv ./floorp-macOS-universal-moz-artifact-dev.dmg ./output/floorp-macOS-universal-moz-artifact-dev.dmg

        - name: Remove needless artifacts 🗑️
          uses: geekyeggo/delete-artifact@v5
          with:
            name: |
              floorp-mac-aarch64-package
              floorp-mac-x86_64-package

        - name: Publish Package Mozilla Artifact for dev 🎁
          uses: actions/upload-artifact@v4
          with:
            name: floorp-mac-universal-moz-artifact-dev
            if-no-files-found: ignore
            path: |
              ./output/

        - name: Publish Package Mozilla Artifact for release 🎁
          uses: actions/upload-artifact@v4
          with:
            name: floorp-mac-universal-moz-artifact-release
            if-no-files-found: ignore
            path: |
              ./floorp-macOS-universal-moz-artifact-release.dmg
