# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

name: "(A) 📦️ Package"

on:
  workflow_dispatch:
    inputs:
      platform:
        type: choice
        options:
          - win-x64
          - linux-x64
      artifact_workflow_run_id:
        type: string
        required: true

run-name: 📦️ Package ${{inputs.platform == 'win-x64' && 'Windows x64' || 'Linux x64'}}
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Allocate Storage
        run: |
          echo Before:
          free -h
          df -h
          
          sudo apt autoremove -y
          sudo apt clean
          sudo rm -rf ./git
          sudo rm -rf /home/linuxbrew
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/local/graalvm
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /etc/apache2
          sudo rm -rf /etc/nginx
          sudo rm -rf /usr/local/share/chrome_driver
          sudo rm -rf /usr/local/share/edge_driver
          sudo rm -rf /usr/local/share/gecko_driver
          sudo rm -rf /usr/share/java
          sudo rm -rf /usr/share/miniconda
          sudo rm -rf /usr/local/share/vcpkg
  
          echo
          echo
          
          echo After:
          free -h
          df -h
      - name: Configure sccache
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - name: setup Rust 🦀
        run: |
          rustup default nightly
          rustup target add x86_64-pc-windows-msvc

          #? https://github.com/mozilla/sccache#known-caveats
          export CARGO_INCREMENTAL=0
      - name: Setup 🪛
        run: |
          cd $GITHUB_WORKSPACE

          # update noraneko to latest
          git submodule update --remote

          cp ./.github/workflows/mozconfigs/win64.mozconfig mozconfig

          sudo apt install msitools -y

          # SCCACHE START
          echo "mk_add_options 'export RUSTC_WRAPPER=/home/runner/.mozbuild/sccache/sccache'" >> mozconfig
          echo "mk_add_options 'export CCACHE_CPP2=yes'" >> mozconfig
          echo "ac_add_options --with-ccache=/home/runner/.mozbuild/sccache/sccache" >> mozconfig
          echo "mk_add_options 'export SCCACHE_GHA_ENABLED=on'" >> mozconfig
          # SCCACHE END

          #if [[ $GHA_debug == 'true' ]]; then
          #  echo "ac_add_options --enable-debug" >> mozconfig
          #fi

          ./mach --no-interactive bootstrap --application-choice browser
      - name: Mach configure
        run: |
          #git apply --ignore-space-change --ignore-whitespace .github/patches/packaging/*.patch
          ./mach configure
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.platform == 'win-x64' && 'noraneko-win-amd64-zstd-full'}}
          run-id: ${{inputs.artifact_workflow_run_id}}
          github-token: ${{github.token}}
          path: obj-x86_64-pc-windows-msvc-cp
      - name: Move files
        run: |
          rm -r obj-x86_64-pc-windows-msvc
          mv obj-x86_64-pc-windows-msvc-cp obj-x86_64-pc-windows-msvc
          chmod -R 777 obj-x86_64-pc-windows-msvc
          
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build noraneko
        run: |
          cd ./noraneko
          pnpm install
          #node --import @swc-node/register/esm-register ./build.ts --build
          cd ..

      - name: package
        run: |
          ./mach build faster
          ./mach package
