# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

name: Pull Upstream
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: "nyanrus_release"
          fetch-depth: 0
      - name: clone upstream
        run: |
          git clone -b release --single-branch https://github.com/mozilla/gecko-dev --depth 1 upstream_release
          rm -rf ./upstream_release/.git ./upstream_release/.github
      - name: copy upstream to this_repo
        run: |
          rsync -aq --progress upstream_release/ temp_release
          cp -r ./nyanrus_release/.git temp_release
          cp -r ./nyanrus_release/.github temp_release
          cp ./nyanrus_release/.gitmodules temp_release
          cp -r ./nyanrus_release/noraneko temp_release
      - name: apply git patches
        run: |
          cd temp_release
          git apply --ignore-space-change --ignore-whitespace .github/patches/*.patch
      - name: push
        run: |
          export FF_VERSION=$(cat browser/config/version.txt)
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "sync upstream gecko-dev $FF_VERSION"
          git push
