# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# © 2023 Floorp Projects & Contributors

on:
  workflow_call:
    inputs:
      release:
        type: boolean
        default: false
      debug:
        type: boolean
        default: true
      package-full:
        type: boolean
        default: false

jobs:
  win-build:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "latest"
    - uses: actions/checkout@v4
      name: Clone 🧬
      with:
        submodules: "recursive"

    - name: Configure sccache
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: setup Rust 🦀
      run: |
        rustup default nightly
        rustup target add x86_64-pc-windows-msvc

        #? https://github.com/mozilla/sccache#known-caveats
        export CARGO_INCREMENTAL=0

    - name: Allocate swap
      run: |
        echo Before:
        free -h
        df -h
        
        echo
        echo
        
        sudo swapoff /mnt/swapfile
        sudo rm /mnt/swapfile
        sudo fallocate -l 10G /mnt/swapfile
        sudo chmod 600 /mnt/swapfile
        sudo mkswap /mnt/swapfile
        sudo swapon /mnt/swapfile

        sudo apt autoremove -y
        sudo apt clean
        sudo rm -rf  ./git
        sudo rm -rf /home/linuxbrew
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/local/graalvm
        sudo rm -rf /usr/local/share/powershell
        sudo rm -rf /usr/local/share/chromium
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo rm -rf /etc/apache2
        sudo rm -rf /etc/nginx
        sudo rm -rf /usr/local/share/chrome_driver
        sudo rm -rf /usr/local/share/edge_driver
        sudo rm -rf /usr/local/share/gecko_driver
        sudo rm -rf /usr/share/java
        sudo rm -rf /usr/share/miniconda
        sudo rm -rf /usr/local/share/vcpkg


        echo
        echo
        
        echo After:
        free -h
        df -h

    - name: Setup 🪛
      run: |
        cd $GITHUB_WORKSPACE

        # update noraneko to latest
        git submodule update --remote

        cp ./.github/workflows/mozconfigs/win64.mozconfig mozconfig

        # Copy Noraneko Branding
        cp -r ./noraneko/gecko/branding/* ./browser/branding/

        sudo apt install msitools -y

        # SCCACHE START
        echo "mk_add_options 'export RUSTC_WRAPPER=/home/runner/.mozbuild/sccache/sccache'" >> mozconfig
        echo "mk_add_options 'export CCACHE_CPP2=yes'" >> mozconfig
        echo "ac_add_options --with-ccache=/home/runner/.mozbuild/sccache/sccache" >> mozconfig
        echo "mk_add_options 'export SCCACHE_GHA_ENABLED=on'" >> mozconfig
        # SCCACHE END

        
        if [[ $GHA_debug == 'true' ]]; then
          echo "ac_add_options --enable-debug" >> mozconfig
          echo "ac_add_options RUSTC_OPT_LEVEL=3" >> mozconfig
        fi
        if [[ $GHA_release == 'true' ]]; then
          echo "ac_add_options --enable-release" >> mozconfig
          # https://searchfox.org/mozilla-central/rev/c169f7d0287c1a6a5dd7469864135e605eed765f/docs/setup/configuring_build_options.rst#259
        fi

        ./mach --no-interactive bootstrap --application-choice browser
      env:
        GHA_debug: ${{inputs.debug}}
        GHA_release: $((inputs.release}}

    - name: Mach Configure
      run: |
        ./mach configure

    - name: Build 🔨
      run: |
        ./mach build
        ./mach package
        rm -rf ~/.cargo

    # Publish START
    - name: rsync binaries
      run: |
        rsync -aqhL --progress obj-x86_64-pc-windows-msvc/dist/bin/ ~/output

    - name: Publish Package🎁
      uses: actions/upload-artifact@v4
      with:
        name: noraneko-win-amd64-dev
        compression-level: 9
        path: ~/output

    - name: Publish Package full🎁
      if: inputs.package-full
      uses: actions/upload-artifact@v4
      with:
        name: noraneko-win-amd64-moz-artifact
        path: obj-x86_64-pc-windows-msvc/dist/noraneko-*.zip
    # Publish END
