# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# © 2023 Floorp Projects & Contributors

name: "(A) ⚒ Windows build"

on:
  workflow_dispatch:
    inputs:
      release:
        type: boolean
        required: true
      debug:
        type: boolean
        required: true
      package-full:
        type: boolean
        required: true
      code-coverage:
        type: boolean
        required: true

run-name: Windows x64 build${{toJSON(inputs.debug) == 'true' && ' Debug' || ''}}${{toJSON(inputs.release) == 'true' && ' Release' || ''}}${{toJSON(inputs.package-full) == 'true' && ' Full' || ''}}${{toJSON(inputs.code-coverage)=='true'&&' codecov'||''}}
jobs:
  run-main:
    name: win-x64
    uses: ./.github/workflows/windows_build.yml
    with:
      debug: ${{inputs.debug}}
      package-full: ${{inputs.package-full}}
      release: ${{inputs.release}}
      code-coverage: ${{inputs.code-coverage}}
